abjective1 = input("Enter an abjective: ")
noun = input("Enter a noun: ")
abjective2 = input("Enter an abjective: ")
verb = input("Enter a verb: ")
abjective3 = input("Enter an abjective: ")

print(f"Today I went to a {abjective1} zoo.")
print(f"In an exhibit, I saw {noun}")
print(f"{noun} was {abjective2} and {verb}ing")
print(f"I was {abjective3}")